name: app

type: 'nodejs:12'

# You can remove this block or set to false to not use the demo strings.
variables:
    env:
        PLATFORMSH_DEMO: true

hooks:
  build: !include
    type: string
    path: platformsh/setup/build.sh
  deploy: !include
    type: string
    path: platformsh/setup/deploy.sh

disk: 256

mounts:
  'registration':
    source: local
    source_path: registration

web:
  commands:
    start: "npm start"
