# This file defines services you want available to your application.

# elasticsearch:
#     type: elasticsearch:7.2
#     disk: 256
#     size: S
# influxdb:
#     type: influxdb:1.7
#     disk: 256
#     size: S
# kafka:
#     type: kafka:2.2
#     disk: 512
#     size: S
# memcached:
#     type: memcached:1.4
#     size: S
# mongodb:
#     type: mongodb:3.6
#     disk: 1024
#     size: S
# mysql:
#     type: mariadb:10.4
#     disk: 256
#     size: S
# postgresql:
#     type: postgresql:11
#     disk: 256
#     size: S
# rabbitmq:
#     type: rabbitmq:3.7
#     disk: 256
#     size: S
# redis:
#     type: redis:5.0
#     size: S
